### ISSUE TITLE
Problem with video stream

### ISSUE THREAD

**Issue by inf1981** [CoyoteProd/libsumo.net#4]
Hi again,

I checked out the new Version but I always get the stream disconnected. See log:

28.05.2018 18:06:49 Info : Add Capabilities: Jump
28.05.2018 18:06:49 Info : Starting Controller
28.05.2018 18:06:49 Info : Add Capabilities: Jump
Sumo 192.168.2.1 is available 
 28.05.2018 18:06:52 Info : Connecting to Jumping sumo...
28.05.2018 18:06:52 Info : Connected to drone - Handshake completed with { "status": 0, "c2d_port": 54321, "arstream_fragment_size": 65000, "arstream_fragment_maximum_number": 4, "arstream_max_ack_interval": -1, "c2d_update_port": 51, "c2d_user_port": 21 }
28.05.2018 18:06:52 Info : [SumoSender] Thread Started
28.05.2018 18:06:52 Info : [SumoReceiver] Thread Started
28.05.2018 18:06:52 Info : Date updated to: 2018-05-28 
28.05.2018 18:06:52 Info : Time updated to: T180652+0000 
28.05.2018 18:06:52 Info : Keyboard Hook installed
28.05.2018 18:06:52 Info : [SumoDisplay] Thread Started
28.05.2018 18:06:52 Info : Piloting Thread Started
28.05.2018 18:06:52 Info : Keyboard Thread Started
28.05.2018 18:06:52 Warn : State of jump load changed: unloaded (1)
28.05.2018 18:06:52 Error : State about the jump motor problem: none (0)
28.05.2018 18:06:52 Info : Media streaming state is: started(1)
28.05.2018 18:06:52 Info : Media streaming state is: stopped(0)
28.05.2018 18:06:52 Info : Drone Name: JumpingSumo-w176542
28.05.2018 18:06:52 Info : Wifi Type:auto_2_4ghz Band:_2_4ghz Channel:2
28.05.2018 18:06:52 Error : [SumoReceiver] socket.recv() timed out with message : Die angegebene Umwandlung ist ungÃ¼ltig.
28.05.2018 18:06:52 Info : [SumoReceiver] Thread Stopped
28.05.2018 18:08:07 Info : Remove Capabilities: Jump

The stream gets killed immediatly, because of a conversion error it seams. 
Any ideas?

Thanks and regards
Mathias

**Comment by CoyoteProd** [comment]
Hello Mathias,
Be  sure that your firewall is disabled...
Seb

**Comment by CoyoteProd** [comment]
Maye its a cast problem...
Compile in debug and see where its stop...
________________________________

**Comment by CoyoteProd** [comment]
Resolved in commit [#39](https://github.com/CoyoteProd/libsumo.net/commit/5250124b27371b574f1f2235113cae2ba02868ce)
